ANDROID: wonder: explicitly include hex.h in debugfs.c
debugfs.c uses mac_pton which is declared in hex.h in the kernel.
Explicitly add this dependency.
When compiled outside the Android environment, I could see:

debugfs.c:214:14: error: implicit declaration of function ‘mac_pton’ [-Wimplicit-function-declaration]
  214 |         if (!mac_pton(buf, wondertap->query_mac_addr)) {
      |              ^~~~~~~~

Change-Id: I963466a63d4dc5644234d6ab055523af02c61777
Signed-off-by: Emmanuel Grumbach <emmanuel.grumbach@intel.com>